# Generated by Django 4.1.4 on 2022-12-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
