FROM python:3.10-slim

WORKDIR /ads_online

EXPOSE 8000


COPY poetry.lock pyproject.toml ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi --no-root


COPY .. .


ENTRYPOINT ["bash", "entrypoint.sh"]

CMD ["python", "manage.py", "runserver"]